AWSTemplateFormatVersion: 2010-09-09
Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: my-test-kz-poc
      Tags:
        - Key: purpose
          Value: poc